import { useState } from "react";
import type { ThemeName } from "../../shared/types";

const timeSlots = ["08:30", "12:15", "17:45", "20:30"];

export function SettingsPage({ theme, onThemeChange }: { theme: ThemeName; onThemeChange: (theme: ThemeName) => void }) {
  const [saved, setSaved] = useState(false);
  const [simulation, setSimulation] = useState(true);
  return <form className="settings-layout" onSubmit={(event) => { event.preventDefault(); setSaved(true); window.setTimeout(() => setSaved(false), 2000); }}>
    <section className="card-surface settings-section"><div className="section-heading"><div><span className="eyebrow">Pilot scope</span><h2>Daily operation</h2></div><span className="mock-badge">Local only</span></div><div className="form-grid"><label>Posts per day<input type="number" min="1" max="12" defaultValue="4" /></label><label>Active accounts<input type="number" min="1" defaultValue="1" /></label><label>Timezone<select defaultValue="Asia/Bangkok"><option>Asia/Bangkok</option></select></label><label>Winner threshold<input type="number" min="0" max="100" defaultValue="75" /></label></div><fieldset><legend>Preferred posting slots</legend><div className="chip-options">{timeSlots.map((slot) => <label key={slot}><input type="checkbox" defaultChecked /><span>{slot}</span></label>)}</div></fieldset></section>
    <section className="card-surface settings-section"><div className="section-heading"><div><span className="eyebrow">Creative</span><h2>Content direction</h2></div></div><label>Caption voice<select defaultValue="friendly"><option value="friendly">Friendly product expert</option><option value="urgent">Urgent deal hunter</option><option value="minimal">Minimal and factual</option></select></label><label>Gemini browser prompt<textarea defaultValue="Write a Thai social caption focused on a clear buyer problem, concrete benefit, honest urgency, and one call to action." /></label><label>Google Flow visual style<textarea defaultValue="Warm editorial product scene, clean composition, mobile-safe negative space, no rendered text, no fake logos." /></label></section>
    <section className="card-surface settings-section"><div className="section-heading"><div><span className="eyebrow">Office skin</span><h2>Theme-ready floor</h2></div></div><div className="theme-picker"><label className={theme === "warm-studio" ? "selected" : ""}><input type="radio" name="theme" checked={theme === "warm-studio"} onChange={() => onThemeChange("warm-studio")} /><span>C</span><b>Warm Studio</b><small>Active assets</small></label><label className={theme === "bright-operations" ? "selected" : ""}><input type="radio" name="theme" checked={theme === "bright-operations"} onChange={() => onThemeChange("bright-operations")} /><span>A</span><b>Bright Operations</b><small>Color shell ready</small></label><label className={theme === "tech-operations" ? "selected" : ""}><input type="radio" name="theme" checked={theme === "tech-operations"} onChange={() => onThemeChange("tech-operations")} /><span>B</span><b>Tech Operations</b><small>Color shell ready</small></label></div></section>
    <section className="card-surface settings-section danger-safe"><div className="section-heading"><div><span className="eyebrow">Execution safety</span><h2>External actions</h2></div></div><label className="switch-row"><span><b>Simulation mode</b><small>Never call Shopee, Gemini, Flow, or Meta while enabled.</small></span><input type="checkbox" checked={simulation} onChange={(event) => setSimulation(event.target.checked)} /></label><label className="switch-row"><span><b>Require publish confirmation</b><small>Recommended even after live connectors are enabled.</small></span><input type="checkbox" defaultChecked /></label><div className="connection-list"><p><i className="ok" /> Local filesystem <b>Ready</b></p><p><i className="ok" /> Google Sheet target <b>Configured</b></p><p><i className="pending" /> Meta Graph API <b>Later</b></p></div></section>
    <div className="settings-actions"><p>{saved ? "Settings saved in this browser prototype." : "Changes are local until the settings API is connected."}</p><button type="submit">Save settings</button></div>
  </form>;
}
