import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { relative, root, walk } from "./source-files.mjs";

const manifests = (await walk()).filter((file) => file.endsWith("package.json") && file !== path.join(root, "package.json"));
const rows = [];
for (const manifestPath of manifests.sort()) {
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  const directory = relative(path.dirname(manifestPath));
  rows.push(`| \`${manifest.name ?? directory}\` | \`${directory}\` | ${manifest.description ?? "Workspace module"} |`);
}
const output = `# Generated code map\n\n> Generated by \`npm run code:map\`. Do not hand-edit.\n\n| Module | Location | Purpose |\n| --- | --- | --- |\n${rows.join("\n")}\n\n## Dependency direction\n\n\`apps -> packages\`, \`services -> packages\`, and \`packages -> packages\`. Packages never import applications or services.\n`;
const directory = path.join(root, "docs", "generated");
await mkdir(directory, { recursive: true });
await writeFile(path.join(directory, "CODEMAP.md"), output);
console.log(`Generated code map for ${rows.length} modules.`);
