import assert from "node:assert/strict";
import { cpSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  checkGeneratedFiles,
  generateCommonV2Source,
  writeGeneratedFiles,
} from "./office-v2-contracts-generate.mjs";

const repositoryRoot = new URL("..", import.meta.url).pathname.replace(/^\//u, "").replaceAll("%20", " ");

test("common V2 generation is byte-identical across repeated renders", () => {
  assert.equal(generateCommonV2Source(repositoryRoot), generateCommonV2Source(repositoryRoot));
});

test("the committed generated file is drift-free", () => {
  assert.equal(checkGeneratedFiles(repositoryRoot), "Office V2 generated contracts are deterministic and drift-free.");
});

test("a changed generated byte fails the drift gate", () => {
  const temporaryRoot = mkdtempSync(join(tmpdir(), "office-v2-contracts-"));
  try {
    cpSync(join(repositoryRoot, "docs"), join(temporaryRoot, "docs"), { recursive: true });
    mkdirSync(join(temporaryRoot, "packages/office-v2-contracts/src/generated"), { recursive: true });
    writeGeneratedFiles(temporaryRoot);
    const outputPath = join(temporaryRoot, "packages/office-v2-contracts/src/generated/common-v2.ts");
    writeFileSync(outputPath, `${readFileSync(outputPath, "utf8")}drift\n`);
    assert.throws(() => checkGeneratedFiles(temporaryRoot), /contract\.generated-drift/);
  } finally {
    rmSync(temporaryRoot, { force: true, recursive: true });
  }
});
