import assert from "node:assert/strict";
import { cpSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import {
  checkGeneratedFiles,
  generateCommonV2Source,
  expectedGeneratedFiles,
  officeV2SchemaDescriptors,
  validateSchemaDescriptors,
  writeGeneratedFiles,
} from "./office-v2-contracts-generate.mjs";

const repositoryRoot = fileURLToPath(new URL("..", import.meta.url));

test("common V2 generation is byte-identical across repeated renders", () => {
  assert.equal(generateCommonV2Source(repositoryRoot), generateCommonV2Source(repositoryRoot));
});

test("the committed generated file is drift-free", () => {
  assert.equal(checkGeneratedFiles(repositoryRoot), "Office V2 generated contracts are deterministic and drift-free.");
});

test("a changed generated byte fails the drift gate", () => {
  const temporaryRoot = mkdtempSync(join(tmpdir(), "office-v2-contracts-"));
  try {
    cpSync(join(repositoryRoot, "docs"), join(temporaryRoot, "docs"), { recursive: true });
    mkdirSync(join(temporaryRoot, "packages/office-v2-contracts/src/generated"), { recursive: true });
    writeGeneratedFiles(temporaryRoot);
    const outputPath = join(temporaryRoot, "packages/office-v2-contracts/src/generated/common-v2.ts");
    writeFileSync(outputPath, `${readFileSync(outputPath, "utf8")}drift\n`);
    assert.throws(() => checkGeneratedFiles(temporaryRoot), /contract\.generated-drift/);
  } finally {
    rmSync(temporaryRoot, { force: true, recursive: true });
  }
});

test("the descriptor registry is explicit and deterministically sorted", () => {
  assert.deepEqual(
    officeV2SchemaDescriptors.map(({ schemaRelativePath }) => schemaRelativePath).toSorted(),
    [
      "docs/office-v2/schemas/action-queue.schema.json",
      "docs/office-v2/schemas/activity-intent.schema.json",
      "docs/office-v2/schemas/asset-catalog.schema.json",
      "docs/office-v2/schemas/asset-family-v2.schema.json",
      "docs/office-v2/schemas/asset-migration.schema.json",
      "docs/office-v2/schemas/asset-review.schema.json",
      "docs/office-v2/schemas/atlas.schema.json",
      "docs/office-v2/schemas/building.schema.json",
      "docs/office-v2/schemas/character-definition.schema.json",
      "docs/office-v2/schemas/common-v2.schema.json",
      "docs/office-v2/schemas/compilation-report.schema.json",
      "docs/office-v2/schemas/compiled-building.schema.json",
      "docs/office-v2/schemas/definition-bundle.schema.json",
      "docs/office-v2/schemas/entity-definition-v2.schema.json",
      "docs/office-v2/schemas/entity-instance.schema.json",
      "docs/office-v2/schemas/export-recipe.schema.json",
      "docs/office-v2/schemas/facility-slot.schema.json",
      "docs/office-v2/schemas/geometry.schema.json",
      "docs/office-v2/schemas/queue-ticket.schema.json",
      "docs/office-v2/schemas/render-part.schema.json",
      "docs/office-v2/schemas/reservation.schema.json",
      "docs/office-v2/schemas/room-template.schema.json",
      "docs/office-v2/schemas/scene-bundle.schema.json",
      "docs/office-v2/schemas/scene-plan.schema.json",
      "docs/office-v2/schemas/semantic-variant.schema.json",
      "docs/office-v2/schemas/simulation-command.schema.json",
      "docs/office-v2/schemas/simulation-event.schema.json",
      "docs/office-v2/schemas/simulation-result.schema.json",
      "docs/office-v2/schemas/simulation-snapshot-v2.schema.json",
      "docs/office-v2/schemas/simulation-trace-v2.schema.json",
      "docs/office-v2/schemas/source-set.schema.json",
      "docs/office-v2/schemas/sprite-frame.schema.json",
      "docs/office-v2/schemas/style-profile.schema.json",
      "docs/office-v2/schemas/world-v2.schema.json",
    ],
  );
  assert.deepEqual(
    validateSchemaDescriptors([...officeV2SchemaDescriptors].reverse()),
    [...officeV2SchemaDescriptors].toSorted((left, right) => left.schemaRelativePath.localeCompare(right.schemaRelativePath)),
  );
});

function officeSchema(id, definitions) {
  return {
    $id: `https://affiliate-operations.example/schemas/office-v2/${id}.schema.json`,
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $defs: definitions,
  };
}

function temporaryOfficeSchemas() {
  const root = mkdtempSync(join(tmpdir(), "office-v2-contracts-multi-"));
  const schemaRoot = join(root, "docs/office-v2/schemas");
  mkdirSync(schemaRoot, { recursive: true });
  const descriptors = [
    {
      schemaRelativePath: "docs/office-v2/schemas/alpha.schema.json",
      generatedRelativePath: "packages/office-v2-contracts/src/generated/alpha.ts",
      schemaId: "https://affiliate-operations.example/schemas/office-v2/alpha.schema.json",
    },
    {
      schemaRelativePath: "docs/office-v2/schemas/beta.schema.json",
      generatedRelativePath: "packages/office-v2-contracts/src/generated/beta.ts",
      schemaId: "https://affiliate-operations.example/schemas/office-v2/beta.schema.json",
    },
  ];
  writeFileSync(join(schemaRoot, "alpha.schema.json"), JSON.stringify(officeSchema("alpha", {
    AlphaHolder: {
      type: "object",
      additionalProperties: false,
      required: ["value"],
      properties: { value: { $ref: "https://affiliate-operations.example/schemas/office-v2/beta.schema.json#/$defs/BetaValue" } },
    },
  }), null, 2));
  writeFileSync(join(schemaRoot, "beta.schema.json"), JSON.stringify(officeSchema("beta", {
    BetaValue: { type: "string" },
  }), null, 2));
  return { root, descriptors };
}

test("multiple schema modules resolve Office references with deterministic imports", () => {
  const { root, descriptors } = temporaryOfficeSchemas();
  try {
    const files = expectedGeneratedFiles(root, descriptors);
    assert.equal(files.size, 2);
    const alpha = files.get("packages/office-v2-contracts/src/generated/alpha.ts");
    assert.match(alpha, /import type \{ BetaValue as BetaBetaValue \} from "\.\/beta\.js";/u);
    assert.match(alpha, /readonly value: BetaBetaValue;/u);
    writeGeneratedFiles(root, descriptors);
    assert.equal(checkGeneratedFiles(root, descriptors), "Office V2 generated contracts are deterministic and drift-free.");
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
});

test("local and cross-schema reference cycles fail closed", () => {
  const { root, descriptors } = temporaryOfficeSchemas();
  try {
    const alphaPath = join(root, descriptors[0].schemaRelativePath);
    const alpha = officeSchema("alpha", {
      Alpha: { $ref: "#/$defs/Beta" },
      Beta: { $ref: "#/$defs/Alpha" },
    });
    writeFileSync(alphaPath, JSON.stringify(alpha, null, 2));
    assert.throws(() => expectedGeneratedFiles(root, [descriptors[0]]), /contract\.generator-cycle/u);

    const betaPath = join(root, descriptors[1].schemaRelativePath);
    writeFileSync(alphaPath, JSON.stringify(officeSchema("alpha", {
      Alpha: { $ref: "https://affiliate-operations.example/schemas/office-v2/beta.schema.json#/$defs/Beta" },
    }), null, 2));
    writeFileSync(betaPath, JSON.stringify(officeSchema("beta", {
      Beta: { $ref: "https://affiliate-operations.example/schemas/office-v2/alpha.schema.json#/$defs/Alpha" },
    }), null, 2));
    assert.throws(() => expectedGeneratedFiles(root, descriptors), /contract\.generator-cycle/u);
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
});

test("descriptor and generated-output collisions fail closed", () => {
  const { root, descriptors } = temporaryOfficeSchemas();
  try {
    assert.throws(
      () => expectedGeneratedFiles(root, [descriptors[0], { ...descriptors[1], generatedRelativePath: descriptors[0].generatedRelativePath }]),
      /contract\.generator-descriptor-collision/u,
    );
    assert.throws(() => expectedGeneratedFiles(root, [descriptors[0], {
      ...descriptors[1],
      schemaId: descriptors[0].schemaId,
    }]), /contract\.generator-descriptor-collision/u);
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
});

test("nested unexpected generated output fails the drift gate", () => {
  const temporaryRoot = mkdtempSync(join(tmpdir(), "office-v2-contracts-unexpected-"));
  try {
    cpSync(join(repositoryRoot, "docs"), join(temporaryRoot, "docs"), { recursive: true });
    writeGeneratedFiles(temporaryRoot);
    const unexpectedPath = join(temporaryRoot, "packages/office-v2-contracts/src/generated/nested/unexpected.ts");
    mkdirSync(join(temporaryRoot, "packages/office-v2-contracts/src/generated/nested"), { recursive: true });
    writeFileSync(unexpectedPath, "export type Unexpected = never;\n");
    assert.throws(() => checkGeneratedFiles(temporaryRoot), /contract\.generated-drift: unexpected generated files/u);
  } finally {
    rmSync(temporaryRoot, { force: true, recursive: true });
  }
});
