export const QUEUE_RUNTIME_VERSION = "office-queue-runtime-v1" as const;
export const QUEUE_POLICY_VERSION = "office-queue-policy-v1" as const;
export type QueuePriorityClass = "durable" | "decorative";
export type QueueTicketState = "waiting" | "acquired" | "yielding" | "released" | "canceled" | "blocked";
export type QueueCleanupReason = "completed" | "canceled" | "timeout" | "target-removed" | "actor-removed" | "preempted" | "route-invalidated" | "failed";
export interface QueueDiagnostic { readonly code: string; readonly context: Readonly<Record<string, string | number | readonly string[]>>; }
export class QueueRuntimeError extends Error {
  readonly code: string;
  readonly context: Readonly<Record<string, string | number | readonly string[]>>;
  constructor(code: string, message: string, context: Readonly<Record<string, string | number | readonly string[]>> = {}) { super(message); this.name = "QueueRuntimeError"; this.code = code; this.context = context; }
}
export interface QueueTicketInput { readonly ticketId: string; readonly intentId: string; readonly actorId: string; readonly priorityClass: QueuePriorityClass; readonly issuedTick: number; readonly enqueueTick: number; readonly resourceKeys: readonly string[]; readonly legalYieldCells?: readonly string[]; readonly lastProgressTick?: number; }
export interface QueueTicket {
  readonly schemaVersion: typeof QUEUE_RUNTIME_VERSION; readonly queuePolicyVersion: typeof QUEUE_POLICY_VERSION; readonly ticketId: string; readonly intentId: string; readonly actorId: string; readonly priorityClass: QueuePriorityClass; readonly issuedTick: number; readonly enqueueTick: number; readonly resourceKeys: readonly string[]; readonly legalYieldCells: readonly string[]; readonly state: QueueTicketState; readonly cleanupGeneration: number; readonly releasedResourceKeys: readonly string[]; readonly acquiredTick?: number; readonly terminalReason?: QueueCleanupReason | "deadlock-no-yield-cell"; readonly yieldCell?: string; readonly diagnostic?: QueueDiagnostic;
}
export interface QueueReservation { readonly schemaVersion: "office-reservation-v1"; readonly reservationId: string; readonly ticketId: string; readonly intentId: string; readonly actorId: string; readonly resourceKey: string; readonly acquiredTick: number; readonly state: "held" | "released"; readonly releasedTick?: number; }
export interface QueueActorProgress { readonly actorId: string; readonly intentId: string; readonly priorityClass: QueuePriorityClass; readonly issuedTick: number; readonly lastProgressTick: number; readonly legalYieldCells: readonly string[]; readonly status: "active" | "yielding" | "blocked"; readonly outcomeTick?: number; }
export interface QueueWaitForEdge { readonly fromActorId: string; readonly toActorId: string; readonly kind: "resource" | "spatial"; readonly resourceKey?: string; readonly createdTick: number; }
export interface QueueState { readonly schemaVersion: typeof QUEUE_RUNTIME_VERSION; readonly queuePolicyVersion: typeof QUEUE_POLICY_VERSION; readonly tick: number; readonly noProgressThreshold: number; readonly tickets: readonly QueueTicket[]; readonly reservations: readonly QueueReservation[]; readonly actors: readonly QueueActorProgress[]; readonly waitForEdges: readonly QueueWaitForEdge[]; }
export interface QueueOperationResult { readonly state: QueueState; readonly changed: boolean; readonly accepted: boolean; readonly ticket?: QueueTicket; readonly blockedResourceKeys?: readonly string[]; readonly blockedByTicketIds?: readonly string[]; readonly releasedResourceKeys?: readonly string[]; readonly diagnostic?: QueueDiagnostic; }
export interface QueueStateOptions { readonly currentTick?: number; readonly noProgressThreshold?: number; }
export interface QueueWaitForCycle { readonly actorIds: readonly string[]; readonly edges: readonly QueueWaitForEdge[]; }
export interface QueueDeadlockResolution { readonly cycle: QueueWaitForCycle; readonly victimActorId: string; readonly victimTicketId?: string; readonly outcome: "yield" | "blocked"; readonly releasedResourceKeys: readonly string[]; readonly yieldCell?: string; readonly diagnostic?: QueueDiagnostic; }
export interface QueueDeadlockResult { readonly state: QueueState; readonly resolutions: readonly QueueDeadlockResolution[]; readonly diagnostics: readonly QueueDiagnostic[]; }
export interface QueueProfileResult { readonly requestCount: number; readonly accepted: number; readonly completed: number; readonly state: QueueState; }

const priorityRank: Record<QueuePriorityClass, number> = { decorative: 0, durable: 1 };
const error = (code: string, message: string, context: Readonly<Record<string, string | number | readonly string[]>> = {}) => new QueueRuntimeError(code, message, context);
const diag = (code: string, context: Readonly<Record<string, string | number | readonly string[]>>): QueueDiagnostic => ({ code, context });

/** Canonical UTF-16 code-unit comparison; locale and render order never enter queue identity. */
export function compareQueueKeys(left: string, right: string): number { for (let i = 0; i < Math.min(left.length, right.length); i += 1) { const difference = left.charCodeAt(i) - right.charCodeAt(i); if (difference !== 0) return difference; } return left.length - right.length; }
function id(value: string, name: string): void { if (typeof value !== "string" || value.length === 0) throw error("simulation.queue-identity-invalid", `${name} must be a non-empty string`, { name }); }
function tick(value: number, name: string): void { if (!Number.isSafeInteger(value) || value < 0) throw error("simulation.queue-tick-invalid", `${name} must be a non-negative safe integer`, { name, value }); }
function priority(value: QueuePriorityClass): void { if (value !== "durable" && value !== "decorative") throw error("simulation.queue-priority-invalid", "priorityClass is not supported", { value }); }

/** Validate and normalize a complete resource set before state mutation. */
export function normalizeQueueResourceKeys(resourceKeys: readonly string[]): readonly string[] {
  if (!Array.isArray(resourceKeys) || resourceKeys.length === 0) throw error("simulation.queue-resource-invalid", "resourceKeys must be non-empty");
  const result = [...resourceKeys];
  for (const key of result) id(key, "resourceKey");
  result.sort(compareQueueKeys);
  for (let i = 1; i < result.length; i += 1) if (result[i] === result[i - 1]) throw error("simulation.queue-resource-duplicate", "resourceKeys must be unique", { resourceKey: result[i] });
  return result;
}
function cells(values: readonly string[] | undefined): readonly string[] {
  if (values === undefined) return [];
  if (!Array.isArray(values)) throw error("simulation.queue-yield-cells-invalid", "legalYieldCells must be an array");
  const result = [...values];
  for (const value of result) id(value, "legalYieldCell");
  result.sort(compareQueueKeys);
  for (let i = 1; i < result.length; i += 1) if (result[i] === result[i - 1]) throw error("simulation.queue-yield-cell-duplicate", "legalYieldCells must be unique", { cell: result[i] });
  return result;
}
function validState(state: QueueState): void { if (state.schemaVersion !== QUEUE_RUNTIME_VERSION || state.queuePolicyVersion !== QUEUE_POLICY_VERSION) throw error("simulation.queue-state-version-invalid", "unsupported queue state version"); tick(state.tick, "state.tick"); tick(state.noProgressThreshold, "noProgressThreshold"); if (state.noProgressThreshold === 0) throw error("simulation.queue-threshold-invalid", "noProgressThreshold must be positive"); }
export function createQueueState(options: QueueStateOptions = {}): QueueState { const currentTick = options.currentTick ?? 0; const noProgressThreshold = options.noProgressThreshold ?? 5; tick(currentTick, "currentTick"); tick(noProgressThreshold, "noProgressThreshold"); if (noProgressThreshold === 0) throw error("simulation.queue-threshold-invalid", "noProgressThreshold must be positive"); return { schemaVersion: QUEUE_RUNTIME_VERSION, queuePolicyVersion: QUEUE_POLICY_VERSION, tick: currentTick, noProgressThreshold, tickets: [], reservations: [], actors: [], waitForEdges: [] }; }
function ticketOrder(left: QueueTicket, right: QueueTicket): number { const p = priorityRank[right.priorityClass] - priorityRank[left.priorityClass]; return p || left.enqueueTick - right.enqueueTick || compareQueueKeys(left.ticketId, right.ticketId); }
export function orderQueueTickets(tickets: readonly QueueTicket[]): readonly QueueTicket[] { return [...tickets].sort(ticketOrder); }
const sortReservations = (values: readonly QueueReservation[]) => [...values].sort((a, b) => compareQueueKeys(a.ticketId, b.ticketId) || compareQueueKeys(a.resourceKey, b.resourceKey));
const sortActors = (values: readonly QueueActorProgress[]) => [...values].sort((a, b) => compareQueueKeys(a.actorId, b.actorId));
const sortEdges = (values: readonly QueueWaitForEdge[]) => [...values].sort((a, b) => compareQueueKeys(a.fromActorId, b.fromActorId) || compareQueueKeys(a.toActorId, b.toActorId) || compareQueueKeys(a.kind, b.kind) || compareQueueKeys(a.resourceKey ?? "", b.resourceKey ?? ""));
const active = (state: QueueState, ticketId: string) => state.tickets.find((value) => value.ticketId === ticketId);
const held = (state: QueueState) => state.reservations.filter((value) => value.state === "held");
const overlap = (left: readonly string[], right: readonly string[]) => left.filter((value) => right.includes(value));
function updateTicket(state: QueueState, idValue: string, update: (value: QueueTicket) => QueueTicket): QueueState { return { ...state, tickets: orderQueueTickets(state.tickets.map((value) => value.ticketId === idValue ? update(value) : value)) }; }
function updateActor(state: QueueState, idValue: string, update: (value: QueueActorProgress) => QueueActorProgress): QueueState { return { ...state, actors: sortActors(state.actors.map((value) => value.actorId === idValue ? update(value) : value)) }; }
function result(state: QueueState, ticketId: string, base: Omit<QueueOperationResult, "state" | "ticket">): QueueOperationResult { const ticket = active(state, ticketId); return ticket === undefined ? { ...base, state } : { ...base, state, ticket }; }
function actorRecord(ticket: QueueTicket, lastProgressTick: number): QueueActorProgress { return { actorId: ticket.actorId, intentId: ticket.intentId, priorityClass: ticket.priorityClass, issuedTick: ticket.issuedTick, lastProgressTick, legalYieldCells: ticket.legalYieldCells, status: "active" }; }

export function enqueueQueueTicket(state: QueueState, input: QueueTicketInput): QueueOperationResult {
  validState(state); id(input.ticketId, "ticketId"); id(input.intentId, "intentId"); id(input.actorId, "actorId"); priority(input.priorityClass); tick(input.issuedTick, "issuedTick"); tick(input.enqueueTick, "enqueueTick"); const resourceKeys = normalizeQueueResourceKeys(input.resourceKeys); const legalYieldCells = cells(input.legalYieldCells); const existing = active(state, input.ticketId);
  if (existing !== undefined) { const same = existing.intentId === input.intentId && existing.actorId === input.actorId && existing.priorityClass === input.priorityClass && existing.issuedTick === input.issuedTick && existing.enqueueTick === input.enqueueTick && JSON.stringify(existing.resourceKeys) === JSON.stringify(resourceKeys) && JSON.stringify(existing.legalYieldCells) === JSON.stringify(legalYieldCells); return { state, changed: false, accepted: false, ticket: existing, diagnostic: diag(same ? "simulation.queue-ticket-duplicate" : "simulation.queue-ticket-conflict", { ticketId: input.ticketId }) }; }
  const lastProgressTick = input.lastProgressTick ?? input.enqueueTick; tick(lastProgressTick, "lastProgressTick"); const next: QueueTicket = { schemaVersion: QUEUE_RUNTIME_VERSION, queuePolicyVersion: QUEUE_POLICY_VERSION, ticketId: input.ticketId, intentId: input.intentId, actorId: input.actorId, priorityClass: input.priorityClass, issuedTick: input.issuedTick, enqueueTick: input.enqueueTick, resourceKeys, legalYieldCells, state: "waiting", cleanupGeneration: 0, releasedResourceKeys: [] };
  return { state: { ...state, tick: Math.max(state.tick, input.enqueueTick), tickets: orderQueueTickets([...state.tickets, next]), actors: sortActors([...state.actors.filter((value) => value.actorId !== next.actorId), actorRecord(next, lastProgressTick)]) }, changed: true, accepted: true, ticket: next };
}

/** Fair, all-or-none acquisition. A failed attempt creates no partial claim. */
export function acquireQueueTicket(state: QueueState, ticketId: string, currentTick = state.tick): QueueOperationResult {
  validState(state); id(ticketId, "ticketId"); tick(currentTick, "currentTick"); const ticket = active(state, ticketId);
  if (ticket === undefined) return { state, changed: false, accepted: false, diagnostic: diag("simulation.queue-ticket-not-found", { ticketId }) };
  if (ticket.state === "acquired") return { state, changed: false, accepted: true, ticket };
  if (ticket.state !== "waiting") return { state, changed: false, accepted: false, ticket };
  const earlier = orderQueueTickets(state.tickets.filter((value) => value.state === "waiting" && value.ticketId !== ticketId && ticketOrder(value, ticket) < 0 && overlap(value.resourceKeys, ticket.resourceKeys).length > 0));
  const heldReservations = held(state).filter((value) => value.ticketId !== ticketId); const occupied = [...new Set(ticket.resourceKeys.filter((key) => heldReservations.some((value) => value.resourceKey === key)))].sort(compareQueueKeys);
  const blockedBy = [...new Set([...earlier.map((value) => value.ticketId), ...heldReservations.filter((value) => occupied.includes(value.resourceKey)).map((value) => value.ticketId)])].sort(compareQueueKeys); const nextState = { ...state, tick: Math.max(state.tick, currentTick) };
  if (occupied.length > 0 || earlier.length > 0) return result(nextState, ticketId, { changed: nextState.tick !== state.tick, accepted: false, blockedResourceKeys: occupied, blockedByTicketIds: blockedBy });
  const reservations: QueueReservation[] = ticket.resourceKeys.map((resourceKey, index) => ({ schemaVersion: "office-reservation-v1", reservationId: `${ticket.ticketId}:reservation:${index + 1}`, ticketId: ticket.ticketId, intentId: ticket.intentId, actorId: ticket.actorId, resourceKey, acquiredTick: currentTick, state: "held" }));
  let acquired: QueueState = { ...nextState, reservations: sortReservations([...state.reservations, ...reservations]) }; acquired = updateTicket(acquired, ticketId, (value) => ({ ...value, state: "acquired", acquiredTick: currentTick })); acquired = updateActor(acquired, ticket.actorId, (value) => ({ ...value, lastProgressTick: currentTick, status: "active" })); return result(acquired, ticketId, { changed: true, accepted: true });
}

const releasedKeys = (state: QueueState, ticketId: string): readonly string[] => [...new Set(held(state).filter((value) => value.ticketId === ticketId).map((value) => value.resourceKey))].sort(compareQueueKeys);
const terminal = (value: QueueTicket) => value.state === "released" || value.state === "canceled" || value.state === "yielding" || value.state === "blocked";
/** Idempotently releases reservations, wait edges, and the stable queue ticket. */
export function cleanupQueueTicket(state: QueueState, ticketId: string, currentTick = state.tick, reason: QueueCleanupReason = "canceled"): QueueOperationResult {
  validState(state); id(ticketId, "ticketId"); tick(currentTick, "currentTick"); const ticket = active(state, ticketId); if (ticket === undefined) return { state, changed: false, accepted: false, diagnostic: diag("simulation.queue-ticket-not-found", { ticketId }) }; const released = releasedKeys(state, ticketId);
  if (terminal(ticket) && released.length === 0) return result(state, ticketId, { changed: false, accepted: true, releasedResourceKeys: ticket.releasedResourceKeys });
  const reservations = sortReservations(state.reservations.map((value) => value.ticketId === ticketId && value.state === "held" ? { ...value, state: "released" as const, releasedTick: currentTick } : value)); const nextReleased = [...new Set([...ticket.releasedResourceKeys, ...released])].sort(compareQueueKeys); let next: QueueState = { ...state, tick: Math.max(state.tick, currentTick), reservations, waitForEdges: sortEdges(state.waitForEdges.filter((edge) => edge.fromActorId !== ticket.actorId && edge.toActorId !== ticket.actorId)) };
  next = updateTicket(next, ticketId, (value) => ({ ...value, state: reason === "completed" ? "released" : "canceled", cleanupGeneration: value.cleanupGeneration + 1, releasedResourceKeys: nextReleased, terminalReason: reason })); next = updateActor(next, ticket.actorId, (value) => ({ ...value, lastProgressTick: currentTick, outcomeTick: currentTick, status: "active" })); return result(next, ticketId, { changed: true, accepted: true, releasedResourceKeys: nextReleased });
}
export const releaseQueueTicket = cleanupQueueTicket;
export function recordQueueProgress(state: QueueState, actorId: string, currentTick: number): QueueState { validState(state); id(actorId, "actorId"); tick(currentTick, "currentTick"); if (!state.actors.some((value) => value.actorId === actorId)) throw error("simulation.queue-actor-not-found", "actor has no queue progress record", { actorId }); return updateActor({ ...state, tick: Math.max(state.tick, currentTick) }, actorId, (value) => ({ ...value, lastProgressTick: currentTick, status: "active" })); }

export function setWaitForEdges(state: QueueState, edges: readonly QueueWaitForEdge[], currentTick = state.tick): QueueState {
  validState(state); tick(currentTick, "currentTick"); const unique = new Map<string, QueueWaitForEdge>();
  for (const edge of edges) { id(edge.fromActorId, "fromActorId"); id(edge.toActorId, "toActorId"); tick(edge.createdTick, "createdTick"); if (edge.kind !== "resource" && edge.kind !== "spatial") throw error("simulation.queue-edge-kind-invalid", "wait-for edge kind is unsupported", { kind: edge.kind }); if (edge.resourceKey !== undefined) id(edge.resourceKey, "resourceKey"); unique.set(`${edge.fromActorId}\u0000${edge.toActorId}\u0000${edge.kind}\u0000${edge.resourceKey ?? ""}`, { ...edge }); }
  return { ...state, tick: Math.max(state.tick, currentTick), waitForEdges: sortEdges([...unique.values()]) };
}
const canonical = (values: readonly string[]): readonly string[] => { let best = [...values]; for (let offset = 1; offset < values.length; offset += 1) { const candidate = [...values.slice(offset), ...values.slice(0, offset)]; if (candidate.join("\u0000") < best.join("\u0000")) best = candidate; } return best; };
export function detectWaitForCycles(state: QueueState): readonly QueueWaitForCycle[] {
  validState(state); const adjacency = new Map<string, readonly string[]>(); for (const edge of sortEdges(state.waitForEdges)) adjacency.set(edge.fromActorId, [...(adjacency.get(edge.fromActorId) ?? []), edge.toActorId]); const actors = [...new Set(state.waitForEdges.flatMap((edge) => [edge.fromActorId, edge.toActorId]))].sort(compareQueueKeys); const cycles = new Map<string, readonly string[]>();
  const visit = (start: string, current: string, path: readonly string[]): void => { for (const next of adjacency.get(current) ?? []) { if (next === start) { const value = canonical(path); cycles.set(value.join("\u0000"), value); } else if (!path.includes(next) && path.length < actors.length) visit(start, next, [...path, next]); } }; for (const actor of actors) visit(actor, actor, [actor]);
  return [...cycles.values()].sort((a, b) => compareQueueKeys(a.join("\u0000"), b.join("\u0000"))).map((actorIds) => ({ actorIds, edges: sortEdges(state.waitForEdges.filter((edge) => actorIds.includes(edge.fromActorId) && actorIds.includes(edge.toActorId))) }));
}
function candidate(state: QueueState, actorId: string): QueueActorProgress { const actor = state.actors.find((value) => value.actorId === actorId); if (actor !== undefined) return actor; const ticket = state.tickets.find((value) => value.actorId === actorId); return ticket === undefined ? { actorId, intentId: `${actorId}:intent`, priorityClass: "durable", issuedTick: 0, lastProgressTick: state.tick, legalYieldCells: [], status: "active" } : actorRecord(ticket, ticket.enqueueTick); }
export function selectDeadlockVictim(state: QueueState, actorIds: readonly string[]): QueueActorProgress { validState(state); if (actorIds.length === 0) throw error("simulation.deadlock-cycle-empty", "a cycle must contain an actor"); return [...actorIds].map((actorId) => candidate(state, actorId)).sort((a, b) => priorityRank[a.priorityClass] - priorityRank[b.priorityClass] || b.issuedTick - a.issuedTick || compareQueueKeys(b.actorId, a.actorId))[0]!; }
export function chooseLegalYieldCell(actorId: string, legalYieldCells: readonly string[]): string | undefined { id(actorId, "actorId"); return cells(legalYieldCells)[0]; }
function resolveCycle(state: QueueState, cycle: QueueWaitForCycle, currentTick: number): { state: QueueState; resolution: QueueDeadlockResolution } {
  const victim = selectDeadlockVictim(state, cycle.actorIds); const ticket = state.tickets.find((value) => value.actorId === victim.actorId && !terminal(value)); const yieldCell = chooseLegalYieldCell(victim.actorId, victim.legalYieldCells.length > 0 ? victim.legalYieldCells : ticket?.legalYieldCells ?? []); const released = ticket === undefined ? [] : releasedKeys(state, ticket.ticketId); let next = state;
  if (ticket !== undefined) { const reservations = sortReservations(state.reservations.map((value) => value.ticketId === ticket.ticketId && value.state === "held" ? { ...value, state: "released" as const, releasedTick: currentTick } : value)); next = { ...state, tick: Math.max(state.tick, currentTick), reservations, waitForEdges: sortEdges(state.waitForEdges.filter((edge) => edge.fromActorId !== victim.actorId && edge.toActorId !== victim.actorId)) }; const noYield = diag("simulation.deadlock-no-yield-cell", { actorId: victim.actorId, ticketId: ticket.ticketId, cycle: cycle.actorIds }); next = updateTicket(next, ticket.ticketId, (value) => ({ ...value, state: yieldCell === undefined ? "blocked" : "yielding", cleanupGeneration: value.cleanupGeneration + 1, releasedResourceKeys: [...new Set([...value.releasedResourceKeys, ...released])].sort(compareQueueKeys), ...(yieldCell === undefined ? { terminalReason: "deadlock-no-yield-cell" as const, diagnostic: noYield } : { terminalReason: "preempted" as const, yieldCell }) })); }
  next = updateActor(next, victim.actorId, (value) => ({ ...value, lastProgressTick: currentTick, outcomeTick: currentTick, status: yieldCell === undefined ? "blocked" : "yielding" })); const noYield = yieldCell === undefined ? diag("simulation.deadlock-no-yield-cell", { actorId: victim.actorId, cycle: cycle.actorIds }) : undefined; return { state: next, resolution: { cycle, victimActorId: victim.actorId, ...(ticket === undefined ? {} : { victimTicketId: ticket.ticketId }), outcome: yieldCell === undefined ? "blocked" : "yield", releasedResourceKeys: released, ...(yieldCell === undefined ? {} : { yieldCell }), ...(noYield === undefined ? {} : { diagnostic: noYield }) } };
}
export function resolveDeadlocks(state: QueueState, currentTick = state.tick): QueueDeadlockResult { validState(state); tick(currentTick, "currentTick"); let next = { ...state, tick: Math.max(state.tick, currentTick) }; const resolutions: QueueDeadlockResolution[] = []; for (const cycle of detectWaitForCycles(state)) { if (!cycle.actorIds.some((actorId) => currentTick - candidate(state, actorId).lastProgressTick >= state.noProgressThreshold)) continue; const resolved = resolveCycle(next, cycle, currentTick); next = resolved.state; resolutions.push(resolved.resolution); } return { state: next, resolutions, diagnostics: resolutions.flatMap((value) => value.diagnostic === undefined ? [] : [value.diagnostic]) }; }
export function simulateQueueProfile(requestCount: 1 | 10 | 15): QueueProfileResult { let state = createQueueState({ noProgressThreshold: 5 }); let accepted = 0; for (let i = 0; i < requestCount; i += 1) state = enqueueQueueTicket(state, { ticketId: `profile-ticket-${String(i + 1).padStart(2, "0")}`, intentId: `profile-intent-${String(i + 1).padStart(2, "0")}`, actorId: `profile-actor-${String(i + 1).padStart(2, "0")}`, priorityClass: i % 3 === 0 ? "durable" : "decorative", issuedTick: i, enqueueTick: i, resourceKeys: [`profile:resource:${String(i + 1).padStart(2, "0")}`], legalYieldCells: [`cell:profile:${String(i + 1).padStart(2, "0")}`] }).state; const serviceTick = state.tick + 1; for (const entry of orderQueueTickets(state.tickets)) { const acquired = acquireQueueTicket(state, entry.ticketId, serviceTick); state = acquired.state; if (acquired.accepted) accepted += 1; state = cleanupQueueTicket(state, entry.ticketId, serviceTick, "completed").state; } return { requestCount, accepted, completed: accepted, state }; }
