import { canonicalHashHex, canonicalJsonBytes, type JsonValue } from "@affiliate-ops/office-v2-contracts";
import { hashSimulationState, simulationCollectionDeclarations } from "./state-hash.ts";

export const REPLAY_RUNTIME_VERSION = "office-replay-runtime-v1" as const;
export const SNAPSHOT_SCHEMA_VERSION = "office-simulation-snapshot-v2" as const;
export const TRACE_SCHEMA_VERSION = "office-simulation-trace-v2" as const;
export const BUG_BUNDLE_VERSION = "office-replay-bug-bundle-v1" as const;
export type ReplayCollections = readonly string[];

export class ReplayRuntimeError extends Error {
  readonly code: string;
  readonly path: string;
  readonly context: Readonly<Record<string, string | number>>;
  constructor(code: string, message: string, path = "", context: Readonly<Record<string, string | number>> = {}) { super(message); this.name = "ReplayRuntimeError"; this.code = code; this.path = path; this.context = context; }
}

export interface ReplayInput { readonly inputId: string; readonly scheduledTick: number; readonly kind: string; readonly payload: JsonValue; readonly payloadDigest?: string; }
export interface ReplayInProgressContext { readonly actionPhase: string; readonly progressTicks: number; readonly resourceKeys: readonly string[]; readonly reservationIds: readonly string[]; readonly targetGeneration: number; readonly worldRevision: number; readonly heldPropState: JsonValue; readonly correlation: { readonly workflowRunId: string; readonly taskId: string; readonly eventId: string; }; }
export interface ReplayWorldReference { readonly id: string; readonly version: number; }
export interface ReplaySnapshot<T extends JsonValue = JsonValue> { readonly schemaVersion: typeof SNAPSHOT_SCHEMA_VERSION; readonly snapshotId: string; readonly engineVersion: string; readonly tickRateHz: 10; readonly tick: number; readonly world: ReplayWorldReference; readonly worldRevision: number; readonly state: T; readonly stateHash: string; readonly completedTick: true; readonly definitionVersion?: string; readonly collectionPointers?: ReplayCollections; readonly inProgress?: ReplayInProgressContext; }
export interface ReplayStepResult<T extends JsonValue = JsonValue> { readonly state: T; readonly results?: readonly JsonValue[]; readonly events?: readonly JsonValue[]; readonly subsystem?: string; }
export type ReplayStep<T extends JsonValue = JsonValue> = (state: T, input: ReplayInput | undefined, tick: number) => ReplayStepResult<T>;
export type ReplayHash<T extends JsonValue = JsonValue> = (state: T, tick: number) => string;
export interface ReplayFrame<T extends JsonValue = JsonValue> { readonly schemaVersion: typeof REPLAY_RUNTIME_VERSION; readonly tick: number; readonly completedTick: true; readonly state: T; readonly stateHash: string; readonly results: readonly JsonValue[]; readonly events: readonly JsonValue[]; readonly subsystem?: string; }
export interface ReplayTrace<T extends JsonValue = JsonValue> { readonly schemaVersion: typeof TRACE_SCHEMA_VERSION; readonly traceId: string; readonly engineVersion: string; readonly initialSnapshot: ReplaySnapshot<T>; readonly inputs: readonly ReplayInput[]; readonly frames: readonly ReplayFrame<T>[]; readonly stateHashes: readonly { readonly tick: number; readonly stateHash: string }[]; readonly finalStateHash: string; }
export interface ReplayRunOptions<T extends JsonValue = JsonValue> { readonly initialState: T; readonly initialTick: number; readonly untilTick: number; readonly inputs: readonly ReplayInput[]; readonly step: ReplayStep<T>; readonly hash?: ReplayHash<T>; readonly collectionPointers?: ReplayCollections; readonly engineVersion?: string; readonly world?: ReplayWorldReference; readonly worldRevision?: number; readonly definitionVersion?: string; readonly traceId?: string; }
export interface ReplayRunResult<T extends JsonValue = JsonValue> { readonly trace: ReplayTrace<T>; readonly frames: readonly ReplayFrame<T>[]; readonly finalState: T; readonly finalStateHash: string; readonly results: readonly JsonValue[]; readonly events: readonly JsonValue[]; }
export interface ReplayRestoreOptions<T extends JsonValue = JsonValue> extends Omit<ReplayRunOptions<T>, "initialState" | "initialTick"> { readonly expectedEngineVersion?: string; readonly expectedWorld?: ReplayWorldReference; readonly expectedWorldRevision?: number; readonly expectedDefinitionVersion?: string; readonly targetSchemaVersion?: string; readonly migrations?: readonly ReplayMigration[]; }
export interface ReplayMigration { readonly fromSchemaVersion: string; readonly toSchemaVersion: string; readonly migrate: (snapshot: ReplaySnapshot) => ReplaySnapshot; }
export interface ReplayDivergence { readonly tick: number; readonly subsystem: string; readonly path: string; readonly expected: JsonValue | undefined; readonly actual: JsonValue | undefined; readonly expectedHash: string | undefined; readonly actualHash: string | undefined; }
export interface ReplayComparison { readonly equal: boolean; readonly divergence?: ReplayDivergence; }
export interface ReplayBugBundleInput<T extends JsonValue = JsonValue> { readonly trace: ReplayTrace<T>; readonly diagnostics: readonly JsonValue[]; readonly relevantState?: JsonValue; readonly divergence?: ReplayDivergence; }
export interface ReplayBugBundle { readonly schemaVersion: typeof BUG_BUNDLE_VERSION; readonly traceId: string; readonly engineVersion: string; readonly traceSchemaVersion: typeof TRACE_SCHEMA_VERSION; readonly snapshotSchemaVersion: typeof SNAPSHOT_SCHEMA_VERSION; readonly inputs: readonly { readonly inputId: string; readonly scheduledTick: number; readonly kind: string; readonly payloadDigest: string }[]; readonly stateHashes: readonly { readonly tick: number; readonly stateHash: string }[]; readonly finalStateHash: string; readonly diagnostics: readonly JsonValue[]; readonly relevantState?: JsonValue; readonly divergence?: ReplayDivergence; }

const fail = (code: string, message: string, path = "", context: Readonly<Record<string, string | number>> = {}): never => { throw new ReplayRuntimeError(code, message, path, context); };
const assertId = (value: string, name: string): void => { if (typeof value !== "string" || value.length === 0) fail("simulation.replay-identity-invalid", `${name} must be non-empty`, name); };
const assertTick = (value: number, name: string): void => { if (!Number.isSafeInteger(value) || value < 0) fail("simulation.replay-tick-invalid", `${name} must be a non-negative safe integer`, name); };
const assertHash = (value: string, name: string): void => { if (typeof value !== "string" || !/^[0-9a-f]{64}$/u.test(value)) fail("simulation.replay-hash-invalid", `${name} must be a lowercase SHA-256 digest`, name); if (/^(.)\1{63}$/u.test(value)) fail("simulation.replay-placeholder-hash", `${name} is a placeholder digest`, name); };
const assertJson = (value: JsonValue, name: string): void => { try { canonicalJsonBytes(value); } catch { fail("simulation.replay-json-invalid", `${name} is not canonical JSON`, name); } };
const pointer = (base: string, key: string): string => `${base}/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`;
const keyOrder = (left: string, right: string): number => { for (let i = 0; i < Math.min(left.length, right.length); i += 1) { const difference = left.charCodeAt(i) - right.charCodeAt(i); if (difference !== 0) return difference; } return left.length - right.length; };

function hashState<T extends JsonValue>(state: T, tick: number, custom: ReplayHash<T> | undefined, pointers: ReplayCollections): string { const value = custom === undefined ? hashSimulationState({ state, collectionDeclarations: simulationCollectionDeclarations(pointers) }).stateHash : custom(state, tick); assertHash(value, "stateHash"); return value; }
function validateProgress(progress: ReplayInProgressContext, snapshot: ReplaySnapshot): void {
  if (typeof progress.actionPhase !== "string" || progress.actionPhase.length === 0 || !Number.isSafeInteger(progress.progressTicks) || progress.progressTicks < 0 || !Number.isSafeInteger(progress.targetGeneration) || progress.targetGeneration < 0 || progress.worldRevision !== snapshot.worldRevision) fail("simulation.replay-incomplete-resource-state", "in-progress state has invalid progress or world context", "/inProgress");
  if (!Array.isArray(progress.resourceKeys) || !Array.isArray(progress.reservationIds) || progress.resourceKeys.length === 0 || progress.resourceKeys.some((value) => typeof value !== "string" || value.length === 0) || progress.reservationIds.some((value) => typeof value !== "string" || value.length === 0)) fail("simulation.replay-incomplete-resource-state", "in-progress state lacks complete resource or reservation context", "/inProgress");
  if (typeof progress.correlation?.workflowRunId !== "string" || typeof progress.correlation.taskId !== "string" || typeof progress.correlation.eventId !== "string") fail("simulation.replay-incomplete-resource-state", "in-progress state lacks workflow correlation", "/inProgress/correlation");
  assertJson(progress.heldPropState, "/inProgress/heldPropState");
}

export function createReplaySnapshot<T extends JsonValue>(input: { readonly state: T; readonly tick: number; readonly snapshotId?: string; readonly stateHash?: string; readonly engineVersion?: string; readonly world?: ReplayWorldReference; readonly worldRevision?: number; readonly definitionVersion?: string; readonly inProgress?: ReplayInProgressContext; readonly hash?: ReplayHash<T>; readonly collectionPointers?: ReplayCollections }): ReplaySnapshot<T> {
  assertTick(input.tick, "tick"); const world = input.world ?? { id: "replay-world", version: 1 }; assertId(world.id, "world.id"); if (!Number.isSafeInteger(world.version) || world.version <= 0) fail("simulation.replay-world-invalid", "world.version must be positive", "/world/version"); const snapshotId = input.snapshotId ?? `replay-snapshot-${input.tick}`; assertId(snapshotId, "snapshotId"); const worldRevision = input.worldRevision ?? 0; assertTick(worldRevision, "worldRevision"); assertJson(input.state, "state"); const collectionPointers = input.collectionPointers ?? []; const stateHash = input.stateHash ?? hashState(input.state, input.tick, input.hash, collectionPointers); assertHash(stateHash, "stateHash"); const snapshot: ReplaySnapshot<T> = { schemaVersion: SNAPSHOT_SCHEMA_VERSION, snapshotId, engineVersion: input.engineVersion ?? "office-engine-v2", tickRateHz: 10, tick: input.tick, world, worldRevision, state: input.state, stateHash, completedTick: true, ...(input.definitionVersion === undefined ? {} : { definitionVersion: input.definitionVersion }), ...(collectionPointers.length === 0 ? {} : { collectionPointers }), ...(input.inProgress === undefined ? {} : { inProgress: input.inProgress }) }; if (snapshot.inProgress !== undefined) validateProgress(snapshot.inProgress, snapshot); return snapshot;
}

export function validateReplaySnapshot<T extends JsonValue>(snapshot: ReplaySnapshot<T>, options: { readonly expectedEngineVersion?: string; readonly expectedWorld?: ReplayWorldReference; readonly expectedWorldRevision?: number; readonly expectedDefinitionVersion?: string; readonly hash?: ReplayHash<T>; readonly collectionPointers?: ReplayCollections } = {}): ReplaySnapshot<T> {
  if (snapshot.schemaVersion !== SNAPSHOT_SCHEMA_VERSION) fail("simulation.replay-version-unknown", "snapshot schema version is unsupported", "/schemaVersion"); if (snapshot.tickRateHz !== 10 || snapshot.completedTick !== true) fail("simulation.replay-restore-boundary-invalid", "restore requires a completed 10 Hz tick boundary", "/tick"); assertTick(snapshot.tick, "tick"); assertId(snapshot.snapshotId, "snapshotId"); assertId(snapshot.engineVersion, "engineVersion"); assertId(snapshot.world.id, "world.id"); if (!Number.isSafeInteger(snapshot.world.version) || snapshot.world.version <= 0) fail("simulation.replay-world-invalid", "world version is invalid", "/world/version"); assertTick(snapshot.worldRevision, "worldRevision"); assertJson(snapshot.state, "state"); assertHash(snapshot.stateHash, "stateHash"); const computed = hashState(snapshot.state, snapshot.tick, options.hash, options.collectionPointers ?? snapshot.collectionPointers ?? []); if (computed !== snapshot.stateHash) fail("simulation.replay-snapshot-hash-mismatch", "snapshot stateHash does not match its hashable state", "/stateHash"); if (options.expectedEngineVersion !== undefined && snapshot.engineVersion !== options.expectedEngineVersion) fail("simulation.replay-definition-incompatible", "snapshot engine version is incompatible", "/engineVersion"); if (options.expectedWorld !== undefined && (snapshot.world.id !== options.expectedWorld.id || snapshot.world.version !== options.expectedWorld.version)) fail("simulation.replay-definition-incompatible", "snapshot world reference is incompatible", "/world"); if (options.expectedWorldRevision !== undefined && snapshot.worldRevision !== options.expectedWorldRevision) fail("simulation.replay-definition-incompatible", "snapshot world revision is incompatible", "/worldRevision"); if (options.expectedDefinitionVersion !== undefined && snapshot.definitionVersion !== options.expectedDefinitionVersion) fail("simulation.replay-definition-incompatible", "snapshot definition version is incompatible", "/definitionVersion"); if (snapshot.inProgress !== undefined) validateProgress(snapshot.inProgress, snapshot); const record = snapshot.state as JsonValue; if (typeof record === "object" && record !== null && !Array.isArray(record) && Object.hasOwn(record, "presentationState")) fail("simulation.snapshot-presentation-state", "presentation state cannot be restored as simulation truth", "/state/presentationState"); return snapshot;
}

function validateInput(input: ReplayInput): void { assertId(input.inputId, "inputId"); assertTick(input.scheduledTick, "scheduledTick"); assertId(input.kind, "kind"); assertJson(input.payload, `/inputs/${input.inputId}/payload`); if (input.payloadDigest !== undefined) assertHash(input.payloadDigest, "payloadDigest"); }
export function migrateReplaySnapshot<T extends JsonValue>(snapshot: ReplaySnapshot<T>, targetSchemaVersion: string = SNAPSHOT_SCHEMA_VERSION, migrations: readonly ReplayMigration[] = []): ReplaySnapshot<T> {
  if (snapshot.schemaVersion === targetSchemaVersion) return snapshot; const seen = new Set<string>(); let current = snapshot; while (current.schemaVersion !== targetSchemaVersion) { if (seen.has(current.schemaVersion)) fail("simulation.replay-migration-cycle", "snapshot migration path contains a cycle", "/schemaVersion"); seen.add(current.schemaVersion); const migration = migrations.find((value) => value.fromSchemaVersion === current.schemaVersion); if (migration === undefined) { const version = Number(current.schemaVersion.split("-v").at(-1)); return fail(Number.isSafeInteger(version) && version > 2 ? "simulation.replay-version-unknown" : "simulation.replay-migration-missing", "no tested snapshot migration path exists", "/schemaVersion", { from: current.schemaVersion, to: targetSchemaVersion }); } const step = migration; if (step.toSchemaVersion === current.schemaVersion) fail("simulation.replay-migration-invalid", "snapshot migration does not advance version", "/schemaVersion"); current = step.migrate(current) as ReplaySnapshot<T>; if (current.schemaVersion !== step.toSchemaVersion) fail("simulation.replay-migration-invalid", "snapshot migration returned an unexpected version", "/schemaVersion"); } return current;
}

/** Execute injected deterministic ticks; inputs and events retain their supplied order. */
export function runReplay<T extends JsonValue>(options: ReplayRunOptions<T>): ReplayRunResult<T> {
  assertTick(options.initialTick, "initialTick"); assertTick(options.untilTick, "untilTick"); if (options.untilTick < options.initialTick) fail("simulation.replay-tick-range-invalid", "untilTick must not precede initialTick"); assertJson(options.initialState, "initialState"); const pointers = options.collectionPointers ?? []; const engineVersion = options.engineVersion ?? "office-engine-v2"; const world = options.world ?? { id: "replay-world", version: 1 }; const worldRevision = options.worldRevision ?? 0; const previous = new Set<string>(); let lastTick = options.initialTick; for (const input of options.inputs) { validateInput(input); if (previous.has(input.inputId)) fail("simulation.replay-input-duplicate", "input IDs must be unique", "/inputs"); previous.add(input.inputId); if (input.scheduledTick <= options.initialTick || input.scheduledTick > options.untilTick) fail("simulation.replay-input-boundary-invalid", "input must be scheduled after the completed initial boundary and within the run", `/inputs/${input.inputId}`); if (input.scheduledTick < lastTick) fail("simulation.replay-input-order-invalid", "ordered inputs must be non-decreasing by scheduled tick", `/inputs/${input.inputId}`); lastTick = input.scheduledTick; }
  const traceId = options.traceId ?? `replay-trace-${options.initialTick}-${options.untilTick}`; assertId(traceId, "traceId"); const initialHash = hashState(options.initialState, options.initialTick, options.hash, pointers); const initialSnapshot = createReplaySnapshot({ state: options.initialState, tick: options.initialTick, snapshotId: `${traceId}:initial`, stateHash: initialHash, engineVersion, world, worldRevision, collectionPointers: pointers, ...(options.definitionVersion === undefined ? {} : { definitionVersion: options.definitionVersion }) }); let state = options.initialState; const frames: ReplayFrame<T>[] = []; const results: JsonValue[] = []; const events: JsonValue[] = []; let cursor = 0;
  for (let currentTick = options.initialTick + 1; currentTick <= options.untilTick; currentTick += 1) { const tickResults: JsonValue[] = []; const tickEvents: JsonValue[] = []; let subsystem: string | undefined; const tickInputs = options.inputs.slice(cursor).filter((input) => input.scheduledTick === currentTick); cursor += tickInputs.length; const apply = tickInputs.length === 0 ? [undefined] : tickInputs; for (const input of apply) { const stepped = options.step(state, input, currentTick); assertJson(stepped.state, "step.state"); state = stepped.state; for (const value of stepped.results ?? []) { assertJson(value, "step.result"); tickResults.push(value); results.push(value); } for (const value of stepped.events ?? []) { assertJson(value, "step.event"); tickEvents.push(value); events.push(value); } if (stepped.subsystem !== undefined) subsystem = stepped.subsystem; } const stateHash = hashState(state, currentTick, options.hash, pointers); frames.push({ schemaVersion: REPLAY_RUNTIME_VERSION, tick: currentTick, completedTick: true, state, stateHash, results: tickResults, events: tickEvents, ...(subsystem === undefined ? {} : { subsystem }) }); }
  const finalStateHash = frames.at(-1)?.stateHash ?? initialHash; const trace: ReplayTrace<T> = { schemaVersion: TRACE_SCHEMA_VERSION, traceId, engineVersion, initialSnapshot, inputs: [...options.inputs], frames, stateHashes: [{ tick: initialSnapshot.tick, stateHash: initialHash }, ...frames.map((frame) => ({ tick: frame.tick, stateHash: frame.stateHash }))], finalStateHash }; return { trace, frames, finalState: state, finalStateHash, results, events };
}

export function restoreReplay<T extends JsonValue>(snapshot: ReplaySnapshot<T>, options: ReplayRestoreOptions<T>): ReplayRunResult<T> { const migrated = migrateReplaySnapshot(snapshot, options.targetSchemaVersion ?? SNAPSHOT_SCHEMA_VERSION, options.migrations ?? []); validateReplaySnapshot(migrated, options); return runReplay({ ...options, initialState: migrated.state, initialTick: migrated.tick }); }
export const replayFromSnapshot = restoreReplay;
export const runDeterministicReplay = runReplay;

function difference(expected: JsonValue | undefined, actual: JsonValue | undefined, path = ""): { path: string; expected: JsonValue | undefined; actual: JsonValue | undefined } | undefined {
  if (Object.is(expected, actual)) return undefined; if (expected === undefined || actual === undefined || typeof expected !== typeof actual || expected === null || actual === null || typeof expected !== "object" || typeof actual !== "object") return { path, expected, actual }; if (Array.isArray(expected) || Array.isArray(actual)) { if (!Array.isArray(expected) || !Array.isArray(actual) || expected.length !== actual.length) return { path, expected, actual }; for (let i = 0; i < expected.length; i += 1) { const found = difference(expected[i]!, actual[i]!, `${path}/${i}`); if (found !== undefined) return found; } return undefined; } const left = expected as { readonly [key: string]: JsonValue }; const right = actual as { readonly [key: string]: JsonValue }; const keys = [...new Set([...Object.keys(left), ...Object.keys(right)])].sort(keyOrder); for (const key of keys) { const found = difference(left[key], right[key], pointer(path, key)); if (found !== undefined) return found; } return undefined;
}
export function firstReplayDivergence<T extends JsonValue>(expected: ReplayRunResult<T> | ReplayTrace<T>, actual: ReplayRunResult<T> | ReplayTrace<T>, subsystem = "simulation"): ReplayDivergence | undefined {
  const left = "trace" in expected ? expected.trace : expected; const right = "trace" in actual ? actual.trace : actual; const count = Math.max(left.stateHashes.length, right.stateHashes.length); for (let i = 0; i < count; i += 1) { const a = left.stateHashes[i]; const b = right.stateHashes[i]; if (a?.tick !== b?.tick || a?.stateHash !== b?.stateHash) { const frameA = left.frames.find((frame) => frame.tick === a?.tick); const frameB = right.frames.find((frame) => frame.tick === b?.tick); const found = frameA !== undefined && frameB !== undefined ? difference(frameA.state, frameB.state) : undefined; return { tick: a?.tick ?? b?.tick ?? 0, subsystem: frameA?.subsystem ?? frameB?.subsystem ?? subsystem, path: found?.path ?? "/stateHash", expected: found?.expected, actual: found?.actual, expectedHash: a?.stateHash, actualHash: b?.stateHash }; } }
  const frameCount = Math.max(left.frames.length, right.frames.length); for (let i = 0; i < frameCount; i += 1) { const a = left.frames[i]; const b = right.frames[i]; if (a === undefined || b === undefined) return { tick: a?.tick ?? b?.tick ?? 0, subsystem: a?.subsystem ?? b?.subsystem ?? subsystem, path: "/frames", expected: a?.state, actual: b?.state, expectedHash: a?.stateHash, actualHash: b?.stateHash }; const found = difference(a.events, b.events) ?? difference(a.results, b.results); if (found !== undefined) return { tick: a.tick, subsystem: a.subsystem ?? b.subsystem ?? subsystem, path: found.path.replace(/^\//u, "/events/"), expected: found.expected, actual: found.actual, expectedHash: a.stateHash, actualHash: b.stateHash }; } return undefined;
}
export function compareReplays<T extends JsonValue>(expected: ReplayRunResult<T> | ReplayTrace<T>, actual: ReplayRunResult<T> | ReplayTrace<T>, subsystem = "simulation"): ReplayComparison { const divergence = firstReplayDivergence(expected, actual, subsystem); return divergence === undefined ? { equal: true } : { equal: false, divergence }; }
export const compareReplayRuns = compareReplays;

function forbidden(value: JsonValue, path = ""): string | undefined { if (Array.isArray(value)) { for (let i = 0; i < value.length; i += 1) { const found = forbidden(value[i]!, `${path}/${i}`); if (found !== undefined) return found; } return undefined; } if (value === null || typeof value !== "object") return undefined; for (const [key, child] of Object.entries(value)) { if (/(cookie|token|password|secret|credential|browser.?profile|connector.?payload|session.?archive)/iu.test(key)) return pointer(path, key); const found = forbidden(child, pointer(path, key)); if (found !== undefined) return found; } return undefined; }
export function createSecretSafeBugBundle<T extends JsonValue>(input: ReplayBugBundleInput<T>): ReplayBugBundle {
  if (input.trace.schemaVersion !== TRACE_SCHEMA_VERSION) fail("simulation.replay-trace-version-invalid", "bug bundle requires trace V2", "/trace/schemaVersion"); const secretPath = forbidden(input.relevantState ?? null) ?? forbidden(input.diagnostics as unknown as JsonValue, "/diagnostics"); if (secretPath !== undefined) fail("simulation.replay-bundle-secret", "bug bundle allowlist rejected a secret-bearing field", secretPath); input.trace.stateHashes.forEach((value) => assertHash(value.stateHash, "stateHash")); assertHash(input.trace.finalStateHash, "finalStateHash"); const inputs = input.trace.inputs.map((value) => ({ inputId: value.inputId, scheduledTick: value.scheduledTick, kind: value.kind, payloadDigest: value.payloadDigest ?? canonicalHashHex({ domain: "office-v2:replay-input", domainVersion: REPLAY_RUNTIME_VERSION, payload: value.payload }) })); inputs.forEach((value) => assertHash(value.payloadDigest, "payloadDigest")); return { schemaVersion: BUG_BUNDLE_VERSION, traceId: input.trace.traceId, engineVersion: input.trace.engineVersion, traceSchemaVersion: TRACE_SCHEMA_VERSION, snapshotSchemaVersion: SNAPSHOT_SCHEMA_VERSION, inputs, stateHashes: input.trace.stateHashes, finalStateHash: input.trace.finalStateHash, diagnostics: [...input.diagnostics], ...(input.relevantState === undefined ? {} : { relevantState: input.relevantState }), ...(input.divergence === undefined ? {} : { divergence: input.divergence }) };
}
